### PR TITLE
Fix `replaceAll()` error in the `oi` command

### PR DESCRIPTION
**Pull request by jamiew**
On my macOS Catalina system, the `oi` command was not working because `String.prototype.replaceAll` appears to be missing (?!). Replacing it with a /g/ `replace()` regex works instead.

In order to submit this PR, I also had to do a few other things:

- Extract and commit the actual editable files
- Add a Makefile to re-zip things
- Re-zip with replaceAll() fix

Lots going on so feedback welcome

Thanks for making and sharing these workflows, they are great.

### CODE REVIEW

**Comment by hauselin** [comment]
Thanks for fixing it! I'll take a look in the next few days. 

It looks like the only change you've made is this line, right?

`query = query.replace(/\"/g, '\"');`

**Comment by jamiew** [comment]
That's correct. I'm happy to break it into two PRs if that's easier to stomach; tried to set it up so easier for others to submit patches too. 

In some further testing escaping quotes doesn't seem to be necessary at all, at least for this command! But not sure if that's just my macOS Catalina or what

**Comment by jamiew** [comment]
Just did some more testing in both browser and Applescript and I don't think the escaping quotes is actually required at all. But don't want to break it for others if so

**Comment by hauselin** [comment]
Ok, thanks! I think I'll just merge your pull request but I'll remove all the extra files that have been created since I don't think they're necessary (except for `Obsidian.alfredworkflow`). 

If I'm correct, we can convert easily between `.alfredworkflow` and `info.plist` by changing the extension `.alfredworkflow` to `.zip` and then unzipping it (which creates `info.plist`), right? Was that how you did it?

**Comment by jamiew** [comment]
Yep that's correct. You can see it in `Makefile` I added:

```
zip Obsidian.alfredworkflow info.plist *.png
```

(zip info.plist and *.png -> Obsidian.alfredworkflow)

So my workflow for testing was to sorta edit inside Alfred, then copied my changes over to info.plist, committed, then rebuilt the zip using `make`

**Pull request merged**
