### PR TITLE
daily note template with utf8 encoding support

### PR DESCRIPTION
**Pull request by wudanyang6**

### CODE REVIEW

**Comment by hauselin** [comment]
Thanks for working on this! I'll take a look next week.

**Comment by wudanyang6** [comment]
> Thanks for working on this! I'll take a look next week.

remind

**Comment by weklund** [comment]
bump @hauselin

**Comment by wudanyang6** [comment]
I’m not sure if it’s compatible with the latest version of Obsidian, so I’m going to close the current PR.

**Comment by wudanyang6** [comment]
I’m not sure if it’s compatible with the latest version of Obsidian, so I’m going to close the current PR.

**Pull request closed without merging**
